name: Deploy Migrations

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:

jobs:
  run-migrations:
    runs-on: ubuntu-latest
    environment: 'Development'

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1

      - name: Link and deploy migrations
        working-directory: ./apps/supabase
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID
          supabase db push
